// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNS.Models;

#nullable disable

namespace QLNS.Migrations
{
    [DbContext(typeof(QlnsContext))]
    [Migration("20231012080918_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLNS.Models.ChamCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GioRaLam")
                        .HasColumnType("datetime")
                        .HasColumnName("gioRaLam");

                    b.Property<DateTime?>("GioVaoLam")
                        .HasColumnType("datetime")
                        .HasColumnName("gioVaoLam");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("idNV");

                    b.Property<string>("MaTrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("maTrangThai");

                    b.Property<int?>("TongSoGio")
                        .HasColumnType("int")
                        .HasColumnName("tongSoGio");

                    b.HasKey("Id")
                        .HasName("PK__ChamCong__3213E83F6CF0BF27");

                    b.HasIndex("IdNv");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("ChamCong", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.CongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameCv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nameCV");

                    b.HasKey("Id")
                        .HasName("PK__CongViec__3213E83FFBB292ED");

                    b.ToTable("CongViec", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.DaoTao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("idNV");

                    b.Property<int?>("IdPbDaoTao")
                        .HasColumnType("int")
                        .HasColumnName("idPbDaoTao");

                    b.Property<string>("MaTrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("maTrangThai");

                    b.Property<string>("NdDaoTao")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayDaoTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThucDt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayKetThucDT");

                    b.HasKey("Id")
                        .HasName("PK__DaoTao__3213E83FE8BA5769");

                    b.HasIndex("IdNv");

                    b.HasIndex("IdPbDaoTao");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("DaoTao", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.HieuSuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("idNV");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text")
                        .HasColumnName("noiDung");

                    b.HasKey("Id")
                        .HasName("PK__HieuSuat__3213E83FA2B64DE2");

                    b.HasIndex("IdNv");

                    b.ToTable("HieuSuat", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.HopDongLaoDong", b =>
                {
                    b.Property<int>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("idNV");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted");

                    b.Property<int?>("IdCv")
                        .HasColumnType("int")
                        .HasColumnName("idCV");

                    b.Property<int?>("IdLuong")
                        .HasColumnType("int")
                        .HasColumnName("idLuong");

                    b.Property<int?>("IdPb")
                        .HasColumnType("int")
                        .HasColumnName("idPB");

                    b.Property<int?>("IdVt")
                        .HasColumnType("int")
                        .HasColumnName("idVT");

                    b.Property<string>("MaTrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("maTrangThai");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayKetThuc");

                    b.Property<DateTime?>("NgayLamViec")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayLamViec");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.HasKey("IdNv");

                    b.HasIndex("IdCv");

                    b.HasIndex("IdPb");

                    b.HasIndex("IdVt");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("HopDongLaoDong", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.KyLuatAndKhenThuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("idNV");

                    b.Property<string>("MaTrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("maTrangThai");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text")
                        .HasColumnName("noiDung");

                    b.HasKey("Id")
                        .HasName("PK__KyLuatAn__3213E83F8CF48620");

                    b.HasIndex("IdNv");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("KyLuatAndKhenThuong", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.LichSuLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted");

                    b.Property<int?>("IdLuong")
                        .HasColumnType("int")
                        .HasColumnName("idLuong");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("idNV");

                    b.Property<int?>("IdPttt")
                        .HasColumnType("int")
                        .HasColumnName("idPTTT");

                    b.Property<string>("MaTrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("maTrangThai");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime")
                        .HasColumnName("ngayThanhToan");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text")
                        .HasColumnName("noiDung");

                    b.Property<int?>("SoNgayNghi")
                        .HasColumnType("int")
                        .HasColumnName("soNgayNghi");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updateAt");

                    b.HasKey("Id");

                    b.HasIndex("IdLuong");

                    b.HasIndex("IdNv");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("LichSuLuong", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.LichSuNghiPhep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted");

                    b.Property<int?>("IdNghiPhep")
                        .HasColumnType("int")
                        .HasColumnName("idNghiPhep");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("idNV");

                    b.Property<string>("MaTrangThai")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("maTrangThai");

                    b.Property<DateTime?>("NgayKetThucNghi")
                        .HasColumnType("date")
                        .HasColumnName("ngayKetThucNghi");

                    b.Property<DateTime?>("NgayNghi")
                        .HasColumnType("date")
                        .HasColumnName("ngayNghi");

                    b.Property<string>("NoiDung")
                        .HasColumnType("ntext")
                        .HasColumnName("noiDung");

                    b.HasKey("Id")
                        .HasName("PK__NghiPhep__3213E83F521BAF72");

                    b.HasIndex("IdNv");

                    b.ToTable("LichSuNghiPhep", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.Luong", b =>
                {
                    b.Property<int>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("idNV");

                    b.Property<decimal?>("LuongCb")
                        .HasColumnType("money")
                        .HasColumnName("luongCB");

                    b.Property<decimal?>("LuongTong")
                        .HasColumnType("money")
                        .HasColumnName("luongTong");

                    b.Property<decimal?>("PhuCap")
                        .HasColumnType("money")
                        .HasColumnName("phuCap");

                    b.HasKey("IdNv")
                        .HasName("PK__Luong__3213E83F23A56B53");

                    b.ToTable("Luong", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("ChuyenNganh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("chuyenNganh");

                    b.Property<string>("FistName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fistName");

                    b.Property<int?>("IdCongViec")
                        .HasColumnType("int")
                        .HasColumnName("idCongViec");

                    b.Property<int?>("IdVitri")
                        .HasColumnType("int")
                        .HasColumnName("idVitri");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lastName");

                    b.Property<string>("MaNv")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("maNV");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime")
                        .HasColumnName("ngaySinh");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("trinhDo");

                    b.HasKey("Id")
                        .HasName("PK__NhanVien__3213E83FDA810A26");

                    b.HasIndex("IdCongViec");

                    b.HasIndex("IdVitri");

                    b.HasIndex(new[] { "MaNv" }, "unique_maNV")
                        .IsUnique()
                        .HasFilter("[maNV] IS NOT NULL");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.NhanVienShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdNnv")
                        .HasColumnType("int")
                        .HasColumnName("idNNV");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("idNV");

                    b.HasKey("Id")
                        .HasName("PK__NhanVien__3213E83F4AAF3997");

                    b.HasIndex("IdNnv");

                    b.HasIndex("IdNv");

                    b.ToTable("NhanVienShip", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.NhomNhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("ntext")
                        .HasColumnName("noiDung");

                    b.HasKey("Id")
                        .HasName("PK__NhomNhan__3213E83F4DCFB09B");

                    b.ToTable("NhomNhanVien", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.PhongBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuAnThamGia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("duAnThamGia");

                    b.Property<int?>("IdNguoiQuanLi")
                        .HasColumnType("int")
                        .HasColumnName("idNguoiQuanLi");

                    b.Property<string>("NamePb")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("namePB");

                    b.Property<int?>("SoLuongNvtg")
                        .HasColumnType("int")
                        .HasColumnName("soLuongNVTG");

                    b.HasKey("Id")
                        .HasName("PK__PhongBan__3213E83FC30D7C7E");

                    b.HasIndex("IdNguoiQuanLi");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.Pttt", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("money")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__PTTT__3213E83FFE114845");

                    b.ToTable("PTTT", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted");

                    b.Property<int?>("IdNghiPhep")
                        .HasColumnType("int")
                        .HasColumnName("idNghiPhep");

                    b.HasKey("Id")
                        .HasName("PK__ThongBao__3213E83F57538971");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.TrangThai", b =>
                {
                    b.Property<string>("Ma")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ma");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Ma");

                    b.ToTable("TrangThai", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.ViTri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameVt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nameVT");

                    b.HasKey("Id")
                        .HasName("PK__ViTri__3213E83F260821AD");

                    b.ToTable("ViTri", (string)null);
                });

            modelBuilder.Entity("QLNS.Models.ChamCong", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "IdNvNavigation")
                        .WithMany("ChamCongs")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__ChamCong__idNV__4BAC3F29");

                    b.HasOne("QLNS.Models.TrangThai", "MaTrangThaiNavigation")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaTrangThai")
                        .HasConstraintName("FK_ChamCong_TrangThai");

                    b.Navigation("IdNvNavigation");

                    b.Navigation("MaTrangThaiNavigation");
                });

            modelBuilder.Entity("QLNS.Models.DaoTao", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "IdNvNavigation")
                        .WithMany("DaoTaos")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__DaoTao__idNV__693CA210");

                    b.HasOne("QLNS.Models.PhongBan", "IdPbDaoTaoNavigation")
                        .WithMany("DaoTaos")
                        .HasForeignKey("IdPbDaoTao")
                        .HasConstraintName("FK__DaoTao__idPbDaoT__6A30C649");

                    b.HasOne("QLNS.Models.TrangThai", "MaTrangThaiNavigation")
                        .WithMany("DaoTaos")
                        .HasForeignKey("MaTrangThai")
                        .HasConstraintName("FK_DaoTao_TrangThai");

                    b.Navigation("IdNvNavigation");

                    b.Navigation("IdPbDaoTaoNavigation");

                    b.Navigation("MaTrangThaiNavigation");
                });

            modelBuilder.Entity("QLNS.Models.HieuSuat", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "IdNvNavigation")
                        .WithMany("HieuSuats")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__HieuSuat__idNV__5CD6CB2B");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QLNS.Models.HopDongLaoDong", b =>
                {
                    b.HasOne("QLNS.Models.CongViec", "IdCvNavigation")
                        .WithMany("HopDongLaoDongs")
                        .HasForeignKey("IdCv")
                        .HasConstraintName("FK__HopDongLao__idCV__59063A47");

                    b.HasOne("QLNS.Models.NhanVien", "IdNvNavigation")
                        .WithOne("HopDongLaoDong")
                        .HasForeignKey("QLNS.Models.HopDongLaoDong", "IdNv")
                        .IsRequired()
                        .HasConstraintName("FK__HopDongLao__idNV__5535A963");

                    b.HasOne("QLNS.Models.PhongBan", "IdPbNavigation")
                        .WithMany("HopDongLaoDongs")
                        .HasForeignKey("IdPb")
                        .HasConstraintName("FK__HopDongLao__idPB__571DF1D5");

                    b.HasOne("QLNS.Models.ViTri", "IdVtNavigation")
                        .WithMany("HopDongLaoDongs")
                        .HasForeignKey("IdVt")
                        .HasConstraintName("FK__HopDongLao__idVT__59FA5E80");

                    b.HasOne("QLNS.Models.TrangThai", "MaTrangThaiNavigation")
                        .WithMany("HopDongLaoDongs")
                        .HasForeignKey("MaTrangThai")
                        .HasConstraintName("FK_HopDongLaoDong_TrangThai");

                    b.Navigation("IdCvNavigation");

                    b.Navigation("IdNvNavigation");

                    b.Navigation("IdPbNavigation");

                    b.Navigation("IdVtNavigation");

                    b.Navigation("MaTrangThaiNavigation");
                });

            modelBuilder.Entity("QLNS.Models.KyLuatAndKhenThuong", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "IdNvNavigation")
                        .WithMany("KyLuatAndKhenThuongs")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__KyLuatAndK__idNV__656C112C");

                    b.HasOne("QLNS.Models.TrangThai", "MaTrangThaiNavigation")
                        .WithMany("KyLuatAndKhenThuongs")
                        .HasForeignKey("MaTrangThai")
                        .HasConstraintName("FK_KyLuatAndKhenThuong_TrangThai");

                    b.Navigation("IdNvNavigation");

                    b.Navigation("MaTrangThaiNavigation");
                });

            modelBuilder.Entity("QLNS.Models.LichSuLuong", b =>
                {
                    b.HasOne("QLNS.Models.Luong", "IdLuongNavigation")
                        .WithMany("LichSuLuongs")
                        .HasForeignKey("IdLuong")
                        .HasConstraintName("FK_LichSuLuong_Luong");

                    b.HasOne("QLNS.Models.NhanVien", "IdNvNavigation")
                        .WithMany("LichSuLuongs")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK_Table_1_NhanVien");

                    b.HasOne("QLNS.Models.TrangThai", "MaTrangThaiNavigation")
                        .WithMany("LichSuLuongs")
                        .HasForeignKey("MaTrangThai")
                        .HasConstraintName("FK_Table_1_TrangThai");

                    b.Navigation("IdLuongNavigation");

                    b.Navigation("IdNvNavigation");

                    b.Navigation("MaTrangThaiNavigation");
                });

            modelBuilder.Entity("QLNS.Models.LichSuNghiPhep", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "IdNvNavigation")
                        .WithMany("LichSuNghiPheps")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK_LichSuNghiPhep_NhanVien");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QLNS.Models.Luong", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "IdNvNavigation")
                        .WithOne("Luong")
                        .HasForeignKey("QLNS.Models.Luong", "IdNv")
                        .IsRequired()
                        .HasConstraintName("FK_Luong_NhanVien");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QLNS.Models.NhanVien", b =>
                {
                    b.HasOne("QLNS.Models.CongViec", "IdCongViecNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdCongViec")
                        .HasConstraintName("FK_NhanVien_CongViec");

                    b.HasOne("QLNS.Models.ViTri", "IdVitriNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdVitri")
                        .HasConstraintName("FK_NhanVien_ViTri");

                    b.Navigation("IdCongViecNavigation");

                    b.Navigation("IdVitriNavigation");
                });

            modelBuilder.Entity("QLNS.Models.NhanVienShip", b =>
                {
                    b.HasOne("QLNS.Models.NhomNhanVien", "IdNnvNavigation")
                        .WithMany("NhanVienShips")
                        .HasForeignKey("IdNnv")
                        .HasConstraintName("FK__NhanVienS__idNNV__7B5B524B");

                    b.HasOne("QLNS.Models.NhanVien", "IdNvNavigation")
                        .WithMany("NhanVienShips")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__NhanVienSh__idNV__7A672E12");

                    b.Navigation("IdNnvNavigation");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QLNS.Models.PhongBan", b =>
                {
                    b.HasOne("QLNS.Models.NhanVien", "IdNguoiQuanLiNavigation")
                        .WithMany("PhongBans")
                        .HasForeignKey("IdNguoiQuanLi")
                        .HasConstraintName("FK__PhongBan__idNguo__412EB0B6");

                    b.Navigation("IdNguoiQuanLiNavigation");
                });

            modelBuilder.Entity("QLNS.Models.CongViec", b =>
                {
                    b.Navigation("HopDongLaoDongs");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QLNS.Models.Luong", b =>
                {
                    b.Navigation("LichSuLuongs");
                });

            modelBuilder.Entity("QLNS.Models.NhanVien", b =>
                {
                    b.Navigation("ChamCongs");

                    b.Navigation("DaoTaos");

                    b.Navigation("HieuSuats");

                    b.Navigation("HopDongLaoDong");

                    b.Navigation("KyLuatAndKhenThuongs");

                    b.Navigation("LichSuLuongs");

                    b.Navigation("LichSuNghiPheps");

                    b.Navigation("Luong");

                    b.Navigation("NhanVienShips");

                    b.Navigation("PhongBans");
                });

            modelBuilder.Entity("QLNS.Models.NhomNhanVien", b =>
                {
                    b.Navigation("NhanVienShips");
                });

            modelBuilder.Entity("QLNS.Models.PhongBan", b =>
                {
                    b.Navigation("DaoTaos");

                    b.Navigation("HopDongLaoDongs");
                });

            modelBuilder.Entity("QLNS.Models.TrangThai", b =>
                {
                    b.Navigation("ChamCongs");

                    b.Navigation("DaoTaos");

                    b.Navigation("HopDongLaoDongs");

                    b.Navigation("KyLuatAndKhenThuongs");

                    b.Navigation("LichSuLuongs");
                });

            modelBuilder.Entity("QLNS.Models.ViTri", b =>
                {
                    b.Navigation("HopDongLaoDongs");

                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
